// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $add from "./routes/add.tsx";
import * as $api_bottles_add_stock_id_ from "./routes/api/bottles/add_stock/[id].ts";
import * as $api_bottles_index from "./routes/api/bottles/index.ts";
import * as $api_bottles_remove_stock_id_ from "./routes/api/bottles/remove_stock/[id].ts";
import * as $bottles from "./routes/bottles.tsx";
import * as $index from "./routes/index.tsx";
import * as $Card from "./islands/Card.tsx";
import * as $FormAddBottle from "./islands/FormAddBottle.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/add.tsx": $add,
    "./routes/api/bottles/add_stock/[id].ts": $api_bottles_add_stock_id_,
    "./routes/api/bottles/index.ts": $api_bottles_index,
    "./routes/api/bottles/remove_stock/[id].ts": $api_bottles_remove_stock_id_,
    "./routes/bottles.tsx": $bottles,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Card.tsx": $Card,
    "./islands/FormAddBottle.tsx": $FormAddBottle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
